version: '3.8'

services:
  php:
    image: php:7.4-apache
    container_name: apache_simulation_view
    restart: always
    ports:
      - 80:80
    volumes:
      - ./Fire-SimulateurView:/var/www/html/
